config/routes.rb
Squawker::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", :registrations => :registrations }

  root 'squeeks#index'
  resources :squeeks, only: [:index, :create, :destroy] do
    resource :favorite, only: [:create]
    get :autocomplete_user_username, :on => :collection
  end
  resources :users, only: [:show]
  resources :relationships, only: [:create]

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :squeek
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :broadcaster, class_name: "User"
  belongs_to :consumer, class_name: "User"
  validates :broadcaster_id, presence: true
  validates :consumer_id, presence: true
end

app/models/squeek.rb
class Squeek < ActiveRecord::Base
  include ActionView::Helpers::SanitizeHelper
  include Rails.application.routes.url_helpers

  attr_accessor :ip_address

  validates_presence_of :body
  validates_presence_of :user
  mount_uploader :image, ImageUploader

  belongs_to :user
  belongs_to :user, :inverse_of => :squeeks

  before_validation :sanitize_body

  before_create :create_mentions, :lookup_location
  after_create :mention_notify

  default_scope { where("hidden is false").order(created_at: :desc) }

  def destroy
    self.hidden = true
    self.save
  end

  def viewable_by? current_user
    return true unless self.consumers_only?
    self.user.consumers.include? current_user or self.user == current_user
  end

  private

  def lookup_location
    result = Geocoder.search(ip_address)[0]
    if result.present? and !result.city.blank?
      self.location = [result.city, result.state].join(", ")
    else
      self.location = "Unknown Location"
    end
  end

  protected

  def create_mentions
    find_mentions
    unless @mentions.empty?
      @mentions.each do |mentioned_user|
        new_string = "<a href='#{user_url(mentioned_user)}'>@#{mentioned_user.username}</a>"
        self.body = self.body.gsub(/(@#{mentioned_user.username})/i,new_string)
      end
    end
  end

  def find_mentions
    @mentions = []
    reg = /(?:@\w+)/
    mentions = self.body.scan(reg).uniq
    mentions.each do |mention|
      mention[0] = ''
      @mentions << User.find_by_username(mention.downcase)
    end
  end

  def mention_notify
    unless @mentions.empty?
      @mentions.each do |mentioned_user|
        NotificationMailer.mention_email(mentioned_user,self.user,self.body).deliver
      end
    end
  end

  def sanitize_body
    self.body = sanitize(self.body, tags: %w(a), attributes: %w(href))
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:twitter]

  extend FriendlyId
  friendly_id :username

  include Gravtastic
  has_gravatar size: 300

  has_many :squeeks, :inverse_of => :user
  has_many :relationships, foreign_key: "consumer_id"
  has_many :reverse_relationships, foreign_key: "broadcaster_id", class_name: "Relationship"
  has_many :broadcasters, through: :relationships, source: :broadcaster
  has_many :consumers, through: :reverse_relationships, source: :consumer
  has_many :favorites
  has_many :favorite_squeeks, through: :favorites, source: :squeek

  validates_uniqueness_of :username
  validates_presence_of :username

  def self.find_for_database_authentication(conditions)
    self.where(:username => conditions[:email]).first || self.where(:email => conditions[:email]).first
  end

  def self.find_for_twitter_oauth(auth)
    where(auth.slice(:provider, :uid)).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.username = "@#{auth.info.nickname}"
        user.password = Devise.friendly_token[0,20]
    end
  end

  def consuming?(broadcaster)
    return unless broadcaster
    relationships.find_by(broadcaster: broadcaster)
  end

  def consume!(broadcaster)
    return unless broadcaster
    relationships.create!(broadcaster: broadcaster)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
    devise_parameter_sanitizer.for(:account_update) << :tagline
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    squeek = Squeek.find_by_id(params[:squeek_id])
    Favorite.create!(user: current_user, squeek: squeek)
    flash[:notice] = "You have favorited #{squeek.user.username}'s squeek: \"#{squeek.body}\""
    redirect_to :root
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def twitter
    @user = User.find_for_twitter_oauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Twitter") if is_navigational_format?
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  protected

  def after_update_path_for(resource)
    user_path(resource)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    @user = User.find(params[:relationship][:broadcaster_id])
    @user.consume!(current_user)
    redirect_to @user
  end
end

app/controllers/squeeks_controller.rb
class SqueeksController < ApplicationController
  before_filter :load_squeeks, only: [:index, :create]
  autocomplete :user, :username, :full => true

  def index
    @squeek = Squeek.new
  end

  def create
    squeek_params = params.require(:squeek).permit(:body, :image, :consumers_only)
    @squeek = current_user.squeeks.new(squeek_params)
    @squeek.ip_address = request.remote_ip
    if @squeek.save
      flash[:notice] = "Your squeek has been posted"
      redirect_to squeeks_path
    else
      flash[:alert] = "Your squeek couldn't be posted. #{@squeek.errors.full_messages.join(" ")}"
      render :index
    end
  end

  def destroy
    squeek = Squeek.find(params[:id])
    squeek.destroy
    flash[:alert] = "Your squeek has been deleted"
    redirect_to :back
  end

  private

  def load_squeeks
    @squeeks = Squeek.page params[:page]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by_username(params[:id])
    @consumers = @user.consumers
    @broadcasters = @user.broadcasters
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Squawker
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    = stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Gabriela|Overlock|Averia+Serif+Libre:300,400,700,300italic'
  %body
    .contain-to-grid
      %nav.top-bar
        %ul.title-area
          %li
            .name
              %h1#title
                = link_to "Squawker", root_path
        %section.top-bar-section
          %ul.right
            - if current_user
              %li= link_to "My Profile", user_path(current_user)
              %li.divider
              %li= link_to "Sign Out", destroy_user_session_path, method: :delete
            - else
              %li= link_to "Sign Up", new_user_registration_path
              %li.divider
              %li= link_to "Sign In", new_user_session_path
  .row
    .small-1.columns
      =image_tag "tucan.png", id: 'tucan'
    .row
      .small-offset-1.small-6.columns
        -if flash.notice
          .alert-box.success.radius
            = flash.notice
        -if flash.alert
          .alert-box.warning.radius
            = flash.alert
  = yield

app/views/notifier/mention_email.html.erb
<!DOCTYPE html>

<html>

  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type'/>
  </head>

  <body>

    <h1>Hi <%@user.name%></h1>

    <p><%@mentioner%> mentioned you in a squeek!</p>
    <p>The squeek was: <%@squeek%></p>

  </body>

</html>

app/views/squeeks/_new.html.haml
= simple_form_for @squeek, :html => {:multipart => true} do |f|
  .inputs
    .row
      .small-6.columns
        = f.input :body, label: 'Squeek here', :autofocus => true, :url => autocomplete_user_username_squeeks_path, :as => :text
      .small-6.columns
        = f.input :image, hint: "An optional image to include with your squeek!"
        = f.input :consumers_only, label: " Consumers only?", checked: false, hint:"If checked, this post will only be visible to the people to which you broadcast squeeks"
    .row
      .small-6.columns
        = f.button :submit, 'Squawk', class: 'button tiny radius'

app/views/squeeks/_squeek.html.haml
-if squeek.viewable_by? current_user
  %li.squeek
    .row
      .small-3.columns
        = link_to squeek.user do
          = image_tag squeek.user.gravatar_url, class: "th radius left"
          %h3.text-center= "@#{squeek.user.username}"
          %p.location= time_ago_in_words(squeek.created_at) + " ago from " + squeek.location
      .small-9.columns
        %p= squeek.body.html_safe
        - if squeek.image.present?
          = image_tag squeek.image_url(:thumb).to_s, class: "th radius"
    .row
      .small-12.columns
        = button_to("Delete", squeek_path(squeek), method: :delete, data: {id: squeek.id }, class: "button right" )
        = link_to "Favorite this squeek", squeek_favorite_path(squeek), method: :post, class: "button right"

app/views/squeeks/index.html.haml
- if user_signed_in?
  .row
    .small-12.columns
      .panel
        %h2 Squeek!
        = render partial: "squeeks/new"
- else
  .row
    .small-9.columns
      .panel
        %p
          = link_to "Sign in", new_user_session_path
          or
          = link_to "Sign up", new_user_registration_path
          to post a squeek.
.row
  .small-9.columns
    %ul.squeeks.squawked
      = render @squeeks
    = paginate @squeeks

app/views/squeeks/new.html.haml
= form_for @squeek do |f|
  = f.label :body, "Squeek here"
  = f.text_field :body
  = f.submit "Squawk"

app/views/users/show.html.haml
.row
  .small-12.columns
    .row
      .small-6.medium-3.columns
        = image_tag @user.gravatar_url, class: "th radius"
      .small-12.medium-6.columns
        %h1= "@#{@user.username}'s profile"
        .panel
          %p= @user.tagline
      .small-12.medium-3.columns
        - if current_user == @user
          = link_to "Edit Your Profile", edit_user_registration_path, class: "button"
        - elsif @user.consuming?(current_user)
          %p You are broadcasting to @#{@user.username}.
        - elsif current_user
          %div#add_consumer_form
            = form_for(current_user.relationships.build(broadcaster_id: @user.id)) do |f|
              = f.hidden_field :broadcaster_id
              = f.submit "Broadcast to @#{@user.username}", class: "button"
.row
  .small-6.columns
    %h2 Squeeks:
    %ul.squeeks.squawked
      = render @user.squeeks

  .small-6.columns
    %h2 Favorites:
    %ul.squeeks.favorites
      = render @user.favorite_squeeks